eureka:
    client:
        serviceUrl:
            defaultZone: http://www.58wxy.com:8761/eureka/
server:
    port: 8080
    context-path: /wkt-entrance

spring:
    application:
      name: wkt-entrance
    thymeleaf:
      prefix: classpath:/templates/
    #包含
    profiles:
      active: dev,all
#日志
logging:
    config: classpath:logback-spring.xml
feign:
    hystrix:
        enabled: true

